### ISSUE TITLE
User can search for a specific city's current weather

### ISSUE THREAD

**Issue by neldaza** [neldaza/In-The-Moment-Weather-Reports#1]
## ⚙️ User can search for a specific city's current weather

The user can type a city into the search bar on the opening page and submit the text in that search bar

## 📐 Functionality

"I will type in the search bar and be able to submit whatever I type in"
## 🖼️ Wireframes

![Screen Shot 2021-11-12 at 5 05 46 PM](https://user-images.githubusercontent.com/88061673/141599894-c74bb482-c82d-4b5c-94a5-ffee78d60086.png)
<img width="921" alt="Screen Shot 2021-11-12 at 5 08 05 PM" src="https://user-images.githubusercontent.com/88061673/141599948-efc4646b-5a29-4efb-8658-a0697c3e9fe8.png">

## ✅ Task List
 
- [x] create HTML/CSS replica of figma
- [x] make sure desktop/mobile compatibility match up with figma
- [x] create form element to put search bar input within
- [x] make sure data is retrieved once search is triggered
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
