### ISSUE TITLE
User can OPTIONALLY submit a photo with a report 

### ISSUE THREAD

**Issue by neldaza** [neldaza/In-The-Moment-Weather-Reports#18]
## ⚙️ Feature

User can choose to optionally submit a photo with their report

## 📐 Functionality

"I will be able to submit a report, with or without a photograph"

## 🖼️ Wireframes
![Screen Shot 2022-03-14 at 10 58 29 PM](https://user-images.githubusercontent.com/88061673/158297508-72d8ab62-734c-4f4d-a27d-c70640ec6d36.png)
![Screen Shot 2022-03-14 at 10 59 08 PM](https://user-images.githubusercontent.com/88061673/158297541-79e6c171-9796-4018-8389-2d915f8ac52a.png)

![Screen Shot 2022-03-14 at 10 59 37 PM](https://user-images.githubusercontent.com/88061673/158297548-f2f4569b-634b-4f54-9e8f-f6c287ff72b3.png)

## ✅ Task List

- [x] Create HTML, and CSS Replica of Figma
- [x] make radio option for viewing image URL input
- [x] if "No" is selected, hide the Image URL input,
- [x] if "Yes" is selected, make the image URL visible, and include it as a part of the report form as a whole
- [x] make reports submittable with and without a photograph
- [x] optimize visuals for mobile, tablet and desktop (media queries)
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
