### ISSUE TITLE
User can view the current weather for a single location

### ISSUE THREAD

**Issue by neldaza** [neldaza/In-The-Moment-Weather-Reports#2]
## ⚙️ Feature

The user can type the name of a city within the search bar, and upon entering, a modal with data representing the current weather in that city, as well as a picture for that city will be displayed
## 📐 Functionality

"Once I enter the name of a city, the current weather for that place will come up!"
## 🖼️ Wireframes

<img width="567" alt="Screen Shot 2021-11-12 at 5 15 27 PM" src="https://user-images.githubusercontent.com/88061673/141600237-104c498e-110c-4c9a-be69-d2d83eb3fac2.png">

<img width="407" alt="Screen Shot 2021-11-12 at 5 16 04 PM" src="https://user-images.githubusercontent.com/88061673/141600284-907e470d-47f3-4abe-a340-7a73c0c1b82c.png">

<img width="888" alt="Screen Shot 2021-11-12 at 5 16 38 PM" src="https://user-images.githubusercontent.com/88061673/141600288-a3f0e609-0186-44ee-9819-86a271c4c09f.png">

<img width="888" alt="Screen Shot 2021-11-12 at 5 16 46 PM" src="https://user-images.githubusercontent.com/88061673/141600299-95675f1e-e66c-492e-87a8-08a268f03bc7.png">

## ✅ Task List
 
- [x] recreate HTML/CSS Copy of figma
- [x] ensure that the search bar is within a form element and once submitted with correct information, changes the page
- [x] ensure that the search result page is hidden initially
- [x] create function to access weather information from API
- [x] create function that based off the input value of the search bar, will return the weather information from the API of a city with what was in the search bar, and hides the search bar page
- [x] ensure that the properties and property values located within the weather API call replace the values of the placeholder/empty weather information inputs  
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
