### ISSUE TITLE
User can create a journal entry for the current weather

### ISSUE THREAD

**Issue by neldaza** [neldaza/In-The-Moment-Weather-Reports#3]
## ⚙️ Feature

User can write in a personal journal entry based off the results of the current weather 
## 📐 Functionality

"I can write down my thoughts on the weather report, and rate how accurate it was!"

## 🖼️ Wireframes

<img width="888" alt="Screen Shot 2021-11-12 at 5 35 27 PM" src="https://user-images.githubusercontent.com/88061673/141600943-506567e7-81dd-4216-bdc7-884caa565783.png">
<img width="395" alt="Screen Shot 2021-11-12 at 5 35 36 PM" src="https://user-images.githubusercontent.com/88061673/141600947-38433e1e-6c6b-4c2d-b6ba-57308429d3eb.png">

<img width="854" alt="Screen Shot 2021-11-12 at 5 36 16 PM" src="https://user-images.githubusercontent.com/88061673/141600948-df4f6508-6a31-460d-8dae-5982c9b575e3.png">
<img width="854" alt="Screen Shot 2021-11-12 at 5 36 22 PM" src="https://user-images.githubusercontent.com/88061673/141600950-611b0cc8-55c6-4794-9711-4e4b5c7782f9.png">

<img width="854" alt="Screen Shot 2021-11-12 at 5 36 28 PM" src="https://user-images.githubusercontent.com/88061673/141600954-159206c9-6db9-40ac-b2b6-38a93d31f46e.png">

## ✅ Task List
 
- [x] create HTML/CSS copies of figma
- [x] ensure that clicking on Create New Report leads to form page 
- [x] add appropriate event listeners to nav bar to be able to navigate freely between pages back and forth between appropriate pages
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
