### ISSUE TITLE
User can create a personal weather journal entry 

### ISSUE THREAD

**Issue by neldaza** [neldaza/In-The-Moment-Weather-Reports#4]
## ⚙️ Feature

User can fill out form in it's entirety with an image and submit it

## 📐 Functionality

'I can write a personal weather report and add a link to my own picture for the entry that I'm writing, and submit it once I'm done!"

## 🖼️ Wireframes

<img width="487" alt="Screen Shot 2021-11-12 at 5 57 53 PM" src="https://user-images.githubusercontent.com/88061673/141601642-02cb4333-94ab-4a9a-b011-cf0f1a823b01.png">

<img width="187" alt="Screen Shot 2021-11-12 at 5 58 11 PM" src="https://user-images.githubusercontent.com/88061673/141601647-1014bfea-8533-4ba1-b5ef-04288c59639b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create appropriate HTML/CSS for picture input
- [x] implement "Go Back" button to anchor back to search result 
- [x] make sure when save button is clicked, that form information is submitted properly to entries 
- [x] allow photo url input to provide user responsiveness by immediately showing up on screen when URL is entered
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
