### ISSUE TITLE
User can view all weather journal reports

### ISSUE THREAD

**Issue by neldaza** [neldaza/In-The-Moment-Weather-Reports#5]
## ⚙️ Feature

User can successfully search a city's weather, write a personal weather report on it, store the report, and go back to it once it is stored

## 📐 Functionality

"This app lets me write down my own weather report, any given day for any city and wether or not the report was accurate, and my own personal take on the accuracy and my view of the weather outside, and I can go back and review past reports for cities that I have logged in the past!"

## 🖼️ Wireframes

<img width="683" alt="Screen Shot 2021-11-12 at 11 26 56 PM" src="https://user-images.githubusercontent.com/88061673/141610187-14c6e449-114f-47fb-bcbe-0b1763b5d3dd.png">
<img width="909" alt="Screen Shot 2021-11-12 at 11 27 19 PM" src="https://user-images.githubusercontent.com/88061673/141610190-1ec5738c-5ba4-409f-99bd-6aaefe2e305a.png">

## ✅ Task List
 
- [x] create appropriate HTML/CSS frames/pages for final output ** dont include images for cities in original reports section for each city**
- [x] create storage for every report and accessibility to it
- [x] create storage for every city and allow accessibility
- [x] ensure that reports are assigned to the correct city 
- [x] ensure a clean DOM tree is made for every new entry on its respective city page
- [x] ensure a clean DOM tree is made for every new city that a report is made on, and that it's cleanly put in reports section
- [x] ensure new pages and anchors for those pages can be made for every new city searched and written about
- [x] ensure all navbar anchors are up to par
- [x] make sure search result clears out if new page is opened 
- [x] make sure form is cleared if form is cancelled, or new page is activated 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
