### ISSUE TITLE
User Can Delete a Report 

### ISSUE THREAD

**Issue by neldaza** [neldaza/In-The-Moment-Weather-Reports#8]
## ⚙️ Feature

User can delete a previously written report, if they no longer want it 

## 📐 Functionality

"If I don't want a report anymore, I can simply delete it"

## 🖼️ Wireframes

![Screen Shot 2021-11-18 at 5 54 27 PM](https://user-images.githubusercontent.com/88061673/142670668-5fb8ab08-8cb4-4c10-a051-cd0c72a641b1.png)

![Screen Shot 2021-11-18 at 5 54 59 PM](https://user-images.githubusercontent.com/88061673/142670690-e18ee61a-ac20-461c-851b-c57ba2143b1a.png)

## ✅ Task List

- [x] create HTML/CSS replica of figma
- [x] Make sure all entries are located within data.entries 
- [x] create function to delete entries and return DOM Tree of new entries without the one that was deleted 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
